services:
  jekyll:
    image: jekyll/jekyll@sha256:15fa79ee6293d7970fe2456fa64ea64bbaf308617b2841e73d9e58cfe09445b6
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle/:/usr/local/bundle
    ports:
      - 4000:4000
    command: jekyll serve --force_polling --drafts
